### ISSUE TITLE
Clicks and random actions

### ISSUE THREAD

**Issue by just4omp** [kajdaq/stunning-chainsaw#9]
Does script has methods of random clicks on icons about 1-10 pixels? May be it has random click on screen to prevent game sleep?
Did  not find it in features.

**Comment by leech69** [comment]
there's an in game option to prevent the game from sleeping. look it for it. inside the game settings i think.

**Comment by just4omp** [comment]
yes i know, that there is ingame option. i just would like to know if script  clicks in same pixels everytime or it has random option

**Comment by kajdaq** [comment]
Ask questions in the forum please.  This is for bugs and feature requests.
